<?php
/**
 * @file
 * Code for the Itomic Geo Stuff.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function itomic_geoaustralia_ctools_plugin_api() {
  return array('version' => 1);
}

/**
 * Implementation of hook_ctools_plugin_dierctory() to let the system know
 * we implement plugins.
 */
function itomic_geoaustralia_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_type
 */
function itomic_geoaustralia_ctools_plugin_type() {
  return array(
    'geocoder_handler' => array(),
  );
}

